In [3]:
# Module 2 — NumPy
import numpy as np

print(np.__version__)

2.4.1


In [2]:
# Lesson 1 — Creating Arrays

# Python list vs NumPy array
lst = [321.35, 319.95, 317.25, 314.45, 311.85]
arr = np.array([321.35, 319.95, 317.25, 314.45, 311.85])

print(type(lst))   # Python list
print(type(arr))   # NumPy array
print(arr)

# The magic — math on entire array at once
# No loop needed
celsius = arr - 273.15
print(celsius)

# Compare with list approach — needs a loop
celsius_list = [t - 273.15 for t in lst]
print(celsius_list)

# Array properties
print(arr.shape)    # dimensions
print(arr.dtype)    # data type
print(len(arr))     # length

<class 'list'>
<class 'numpy.ndarray'>
[321.35 319.95 317.25 314.45 311.85]
[48.2 46.8 44.1 41.3 38.7]
[48.200000000000045, 46.80000000000001, 44.10000000000002, 41.30000000000001, 38.700000000000045]
(5,)
float64
5


In [4]:
# Lesson 2 — Array Operations and Boolean Masking

lst_celsius = np.array([48.2, 46.8, 44.1, 41.3, 38.7])
ndvi_values = np.array([0.143, 0.120, 0.161, 0.273, 0.429])

# Basic statistics — no loops needed
print(f"Max LST:     {lst_celsius.max():.1f}°C")
print(f"Min LST:     {lst_celsius.min():.1f}°C")
print(f"Mean LST:    {lst_celsius.mean():.1f}°C")
print(f"Std Dev:     {lst_celsius.std():.2f}")

# Math between two arrays — element by element
heat_stress = lst_celsius * (1 - ndvi_values)
print(f"\nHeat stress scores: {heat_stress.round(2)}")

# Boolean masking — find zones above 44°C without a loop
mask = lst_celsius > 44
print(f"\nMask: {mask}")
print(f"Hot zones: {lst_celsius[mask]}")
print(f"Zones above 44°C: {mask.sum()}")
print(f"NDVI of hot zones: {ndvi_values[mask]}")

Max LST:     48.2°C
Min LST:     38.7°C
Mean LST:    43.8°C
Std Dev:     3.48

Heat stress scores: [41.31 41.18 37.   30.03 22.1 ]

Mask: [ True  True  True False False]
Hot zones: [48.2 46.8 44.1]
Zones above 44°C: 3
NDVI of hot zones: [0.143 0.12  0.161]


In [5]:
# Lesson 3 — 2D Arrays (Satellite Images)

# A real Landsat image is a 2D grid of pixel values
# Let's create a tiny 5x5 LST image of Jaipur
# Each number = temperature of one 30m x 30m pixel

lst_image = np.array([
    [48.2, 47.1, 46.8, 45.2, 43.1],
    [47.5, 48.9, 47.2, 44.8, 42.3],
    [46.1, 45.8, 43.2, 41.5, 39.8],
    [44.3, 43.7, 41.8, 39.2, 37.5],
    [42.1, 40.8, 38.9, 36.2, 34.8],
])

# Shape — rows x columns
print(f"Image shape: {lst_image.shape}")
print(f"Total pixels: {lst_image.size}")
print(f"Dimensions: {lst_image.ndim}")

# Access individual pixels
print(f"\nTop-left pixel: {lst_image[0, 0]}°C")
print(f"Center pixel: {lst_image[2, 2]}°C")
print(f"Bottom-right pixel: {lst_image[4, 4]}°C")

# Slicing rows and columns
print(f"\nFirst row: {lst_image[0]}")
print(f"First column: {lst_image[:, 0]}")
print(f"Top-left 3x3 block:\n{lst_image[0:3, 0:3]}")

# Statistics on entire image
print(f"\nImage stats:")
print(f"Max LST: {lst_image.max():.1f}°C")
print(f"Min LST: {lst_image.min():.1f}°C")
print(f"Mean LST: {lst_image.mean():.1f}°C")

# Boolean mask on 2D image — find all critical pixels
critical_mask = lst_image > 46
print(f"\nCritical pixels (>46°C):\n{critical_mask}")
print(f"Number of critical pixels: {critical_mask.sum()}")
print(f"Critical pixel values: {lst_image[critical_mask]}")

Image shape: (5, 5)
Total pixels: 25
Dimensions: 2

Top-left pixel: 48.2°C
Center pixel: 43.2°C
Bottom-right pixel: 34.8°C

First row: [48.2 47.1 46.8 45.2 43.1]
First column: [48.2 47.5 46.1 44.3 42.1]
Top-left 3x3 block:
[[48.2 47.1 46.8]
 [47.5 48.9 47.2]
 [46.1 45.8 43.2]]

Image stats:
Max LST: 48.9°C
Min LST: 34.8°C
Mean LST: 43.1°C

Critical pixels (>46°C):
[[ True  True  True False False]
 [ True  True  True False False]
 [ True False False False False]
 [False False False False False]
 [False False False False False]]
Number of critical pixels: 7
Critical pixel values: [48.2 47.1 46.8 47.5 48.9 47.2 46.1]


In [6]:
# Lesson 4 — NumPy for Tapascan pipeline

# Simulate a real pipeline step
# Convert raw Landsat Band 10 digital numbers to LST

# Raw Band 10 values (what Landsat actually gives you)
band10_raw = np.array([
    [22145, 22089, 21934, 21756, 21523],
    [22078, 22234, 22012, 21834, 21456],
    [21934, 21867, 21645, 21423, 21234],
    [21756, 21678, 21456, 21234, 21012],
    [21523, 21345, 21123, 20934, 20756],
])

# Step 1 — Apply Landsat scale factors
# Official formula: LST_kelvin = raw * 0.00341802 + 149.0
lst_kelvin = band10_raw * 0.00341802 + 149.0

# Step 2 — Convert to Celsius
lst_celsius = lst_kelvin - 273.15

print("LST in Celsius:")
print(lst_celsius.round(1))

# Step 3 — Normalize NDVI (0 to 1 range)
ndvi_raw = np.array([
    [0.12, 0.15, 0.18, 0.22, 0.31],
    [0.14, 0.11, 0.16, 0.24, 0.33],
    [0.18, 0.19, 0.25, 0.31, 0.38],
    [0.22, 0.24, 0.31, 0.38, 0.42],
    [0.31, 0.33, 0.38, 0.42, 0.48],
])

# Step 4 — Compute heat stress index
heat_stress = lst_celsius * (1 - ndvi_raw)
print("\nHeat stress index:")
print(heat_stress.round(1))

# Step 5 — Find hottest 20% of pixels
threshold = np.percentile(lst_celsius, 80)
print(f"\n80th percentile threshold: {threshold:.1f}°C")
hot_mask = lst_celsius > threshold
print(f"Hot pixels: {hot_mask.sum()} out of {lst_celsius.size}")

# Step 6 — Mean LST of hot pixels only
print(f"Mean LST of hot pixels: {lst_celsius[hot_mask].mean():.1f}°C")
print(f"Mean LST of all pixels: {lst_celsius.mean():.1f}°C")

LST in Celsius:
[[-48.5 -48.6 -49.2 -49.8 -50.6]
 [-48.7 -48.2 -48.9 -49.5 -50.8]
 [-49.2 -49.4 -50.2 -50.9 -51.6]
 [-49.8 -50.1 -50.8 -51.6 -52.3]
 [-50.6 -51.2 -52.  -52.6 -53.2]]

Heat stress index:
[[-42.6 -41.4 -40.3 -38.8 -34.9]
 [-41.9 -42.9 -41.1 -37.6 -34. ]
 [-40.3 -40.  -37.6 -35.1 -32. ]
 [-38.8 -38.  -35.1 -32.  -30.4]
 [-34.9 -34.3 -32.2 -30.5 -27.7]]

80th percentile threshold: -49.1°C
Hot pixels: 5 out of 25
Mean LST of hot pixels: -48.6°C
Mean LST of all pixels: -50.3°C


In [7]:
# Lesson 4 — Fixed with realistic Band 10 values

band10_raw = np.array([
    [28145, 28089, 27934, 27756, 27523],
    [28078, 28234, 28012, 27834, 27456],
    [27934, 27867, 27645, 27423, 27234],
    [27756, 27678, 27456, 27234, 27012],
    [27523, 27345, 27123, 26934, 26756],
])

# Step 1 — Apply Landsat scale factors
lst_kelvin = band10_raw * 0.00341802 + 149.0

# Step 2 — Convert to Celsius
lst_celsius = lst_kelvin - 273.15

print("LST in Celsius:")
print(lst_celsius.round(1))

# Step 3 — NDVI grid
ndvi_raw = np.array([
    [0.12, 0.15, 0.18, 0.22, 0.31],
    [0.14, 0.11, 0.16, 0.24, 0.33],
    [0.18, 0.19, 0.25, 0.31, 0.38],
    [0.22, 0.24, 0.31, 0.38, 0.42],
    [0.31, 0.33, 0.38, 0.42, 0.48],
])

# Step 4 — Heat stress index
heat_stress = lst_celsius * (1 - ndvi_raw)
print("\nHeat stress index:")
print(heat_stress.round(1))

# Step 5 — Hottest 20% of pixels
threshold = np.percentile(lst_celsius, 80)
print(f"\n80th percentile threshold: {threshold:.1f}°C")
hot_mask = lst_celsius > threshold
print(f"Hot pixels: {hot_mask.sum()} out of {lst_celsius.size}")

# Step 6 — Compare means
print(f"Mean LST of hot pixels: {lst_celsius[hot_mask].mean():.1f}°C")
print(f"Mean LST of all pixels: {lst_celsius.mean():.1f}°C")

LST in Celsius:
[[-27.9 -28.1 -28.7 -29.3 -30.1]
 [-28.2 -27.6 -28.4 -29.  -30.3]
 [-28.7 -28.9 -29.7 -30.4 -31.1]
 [-29.3 -29.5 -30.3 -31.1 -31.8]
 [-30.1 -30.7 -31.4 -32.1 -32.7]]

Heat stress index:
[[-24.6 -23.9 -23.5 -22.8 -20.8]
 [-24.2 -24.6 -23.9 -22.  -20.3]
 [-23.5 -23.4 -22.2 -21.  -19.3]
 [-22.8 -22.5 -20.9 -19.3 -18.5]
 [-20.8 -20.6 -19.5 -18.6 -17. ]]

80th percentile threshold: -28.6°C
Hot pixels: 5 out of 25
Mean LST of hot pixels: -28.1°C
Mean LST of all pixels: -29.8°C
